apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meshguard
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - api.yaml
  - web.yaml
  - workers.yaml
  - relay.yaml
  - cloudflared.yaml
