# syntax=docker/dockerfile:1.4
FROM node:22-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/api/package.json apps/api/
COPY packages/auth/package.json packages/auth/
COPY packages/config/package.json packages/config/
COPY packages/db/package.json packages/db/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm fetch

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile \
    --filter @mesh/api... \
    --filter mesh

RUN pnpm turbo run build --filter=@mesh/api^...

CMD ["pnpm", "-F", "@mesh/api", "dev"]
